### ISSUE TITLE
Errors and Warnings

### ISSUE THREAD

**Issue by thinkyhead** [ameyer/Arduino-L6470#2]
```
.piolibdeps/3cd0993/L6470.h:189:0: warning: "DEC" redefined
#define DEC                  0x06
```
This name is defined by `arduino/Print.h` as a flag to print in base 10.

```
Serial.println('good to go');
Serial.println('Comm issue');
```
These strings should be double-quoted. A PR for that is pending.

**Comment by ameyer** [comment]
I never finished this project (started 6 years ago) and don't have the part to even test it anymore so I made you a collaborator on it. Feel free to make changes as needed.

**Comment by thinkyhead** [comment]
Thanks! So I'm not confused that this is the source that Arduino downloads automagically?

**Comment by ameyer** [comment]
Wow! Really? Arduino links to this project for this part? How can I see this in action?

I should make a note in the read me or something that it was never finished. I just assumed that someone else would have written a better library in the past 6 years.

**Comment by ameyer** [comment]
I think I misunderstood your comment. What did you mean by " So I'm not confused that this is the source that Arduino downloads automagically?"

**Comment by thinkyhead** [comment]
Ah, nope. I downloaded it myself. But Marlin recommends this. So I can patch it up and make it an official download that the IDE sees.
```cpp
/**
 * Enable this section if you have L6470 motor drivers.
 * You need to import the L6470 library into the Arduino IDE for this.
 * (https://github.com/ameyer/Arduino-L6470)
 */
```

**Comment by thinkyhead** [comment]
…and also PlatformIO. They just need to see a `.json` file in the repo.
